/***********************************************************************/
/*                                                                     */
/*  FILE        :cstartdef.h                                           */
/*  DATE        :Tue, Dec 14, 2010                                     */
/*  DESCRIPTION :define the size of stack.                             */
/*  CPU GROUP   :2A                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
#define __STACKSIZE__    0x100        // user stack
#define __ISTACKSIZE__   0x100        // interrupt stack
#define __HEAPSIZE__     0x00        // heap size
#define __STANDARD_IO__  0 			 // use standard I/O (ex printf)
#define __WATCH_DOG__    0 			 // When watchdog is made effective after reset, here is set to 1.
